### PR TITLE
Add option for automatic double puppeting

### PR DESCRIPTION
**Pull request by tulir**
When `bridge` -> `loginSharedSecret` is set in the config, the bridge will use [matrix-synapse-shared-secret-auth](https://github.com/devture/matrix-synapse-shared-secret-auth) to transparently enable double puppeting after the first successful `link` command.

Only works for users on the same homeserver as the bridge.

### CODE REVIEW

**Comment by Sorunome** [comment]
If soru understands this correctly the AS doesn't necessarily have to be on the same homeserver as the shared login module thing? So wouldn't a map of homeserver to shared secret make more sense?

**Comment by Sorunome** [comment]
Also, how does this obtain the homeserver URL from the mxid? It could use the existing .well-known resolution

**Comment by Sorunome** [comment]
And maybe for those who don't have .well-known configured an optional homeserver name --> homeserver url mapping.....however that probably is a separate PR. That would also fix https://github.com/matrix-discord/mx-puppet-discord/issues/22 rather elegantly

**Comment by Sorunome** [comment]
Added the homeserver URL mapping in https://github.com/Sorunome/mx-puppet-bridge/commit/ba666eac00703e6fda776470d017dc5b34d3b15c

**Comment by tulir** [comment]
Changed login shared secret config option into a map

**Comment by Sorunome** [comment]
Awesome, thanks a lot!

**Pull request merged**
